#page title
page_title                                : SafeTimer                                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                          # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/apple-store/id1512032981?pt=121500132&ct=web&mt=8  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://hortelanos.net/contacto/          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SafeTimer                                 # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Gratis                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : La app que te ayuda a controlar el uso de mascarillas

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hortelanos                                
your_link                                 : https://hortelanos.net                     
your_city                                 : Vitoria-Gasteiz                                
email_address                             : miguel@hortelanos.net
facebook_username                         :                                           
instagram_username                        : hortelanos
twitter_username                          : 
github_username                           : Hortelanos/SafeTimer
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Protégete a ti y a los demás
    description                           : Junto a la distancia social, las mascarillas son la mejor herramienta que tenemos hoy en día para hacer frente al COVID-19. No sólo es importante llevarla, también saber colocársela y no utilizarla más tiempo para el que han sido diseñadas.
    fontawesome_icon_name                 : heart
    
  - title                                 : Te avisa cuando tienes que cambiar la mascarilla
    description                           : Crea tantos temporizadores como mascarillas estés usando en ese momento. La app se encarga de recordar cuánto tiempo de uso le queda a cada una. Llegado el momento, te enviará una notificación para que la cambies.
    fontawesome_icon_name                 : heart

  - title                                 : Gratis y de Código Abierto
    description                           : SafeTimer ha sido desarrollada de manera altruista por Hortelanos para contribuir a superar la crisis sanitaria. Por eso, es totalmente gratuita (ni compras in-app, ni anuncios) y su código está publicado en Github. La ayuda es bienvenida.
    fontawesome_icon_name                 : code-branch

  - title                                 : También en tu Apple Watch
    description                           : Además de en iPhone, SafeTimer está disponible para Apple Watch. La app es totalmente independiente, no necesitas tener tu teléfono para usarla.
    fontawesome_icon_name                 : clock

  - title                                 : Sincronización en la nube
    description                           : Todos los temporizadores que crees para tus mascarillas se sincronizan en la nube con iCloud. Así puedes usar SafeTimer en tu móvil o tu reloj sin mayor problema.
    fontawesome_icon_name                 : sync
  
  - title                                 : Disponible en 4 idiomas
    description                           : La app está disponible en Castellano, Euskera, Inglés y Francés. Si quieres ayudarnos a traducirla a otros idiomas escríbenos un mail.
    fontawesome_icon_name                 : language

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF5959"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#FF5959"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#FF5959"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown